a=input('小狗需要什么东西呢')
print(a,type(a))
#录入两个整数，计算两个整数的和
b=input('请输入一个数')
c=input('请输入另一个数')#注意：input输入的内容都是str
b=int(b)
c=int(c)
print(b+c)
b1=int(input('请输入一个数：'))
c1=int(input('请输入另一个数：'))
print(b1+c1)